### ISSUE TITLE
I cannot connect websocket after deployment

### ISSUE THREAD

**Issue by huaichao569** [Deviaphan/Versus#1]
hello
I cannot connect websocket after deployment, may I ask what is your deployment procedure, thank you!

**Comment by Deviaphan** [comment]
Unzip. Done.

I need more info. You build own websocket app or try to connect with brower (localhost:9090)?

In the releases section there is only the StreamDeck plugin.
Install 'Versus' from this link: https://obsproject.com/forum/resources/versus-%E2%93%87evolution-scoreboard.1339/

**Comment by huaichao569** [comment]
Yes, I built my own versus, and after starting the service, the access to the page worked, but the scores set could not be updated to the page, and the viewing console was a websocket connection failure.
Because of the StreamDeck?

**Comment by Deviaphan** [comment]
Versus can works without StreamDeck, it's just plugin. No differents between StreamDeck and any Web-Browser.
Version from OBS-forum works fine for you or the same issue?
Do you copy "themes" folder to you output directory?

Copy errors from console.

**Comment by Deviaphan** [comment]
If you connect through LAN/WAN you need open ports in your router (port-forwarding) and firewall.

**Comment by huaichao569** [comment]
1. Use the program you publish can be used
2. I use the latest source code in vs2022 to compile the output exe chorme console prompt "updateData.js:89 WebSocket connection to 'ws://localhost:9091/' failed:"
3. The Qt framework uses version 6.6.0

**Comment by huaichao569** [comment]
![Uploading 1.png…]()

**Comment by huaichao569** [comment]
![1](https://github.com/Deviaphan/Versus/assets/2987000/f8e990ce-2059-4d79-bd10-d3f0982e313e)

**Comment by huaichao569** [comment]
![2](https://github.com/Deviaphan/Versus/assets/2987000/46858de9-39bb-47c4-8c09-584f7663579b)

**Comment by huaichao569** [comment]
Is there anything you should pay attention to when building?

**Comment by Deviaphan** [comment]
> 2\. WebSocket connection to 'ws://localhost:9091/' failed:"

Doesn't it write in the console about the reason for the failure? Browser version?

**Comment by Deviaphan** [comment]
I use last MSVC version: 17.7.4. No tricks.

**Comment by Deviaphan** [comment]
> 'ws://localhost:9091**/**'

My version without this **/**
Try to edit settings and change 'localhost' to you local IP (e.g. 192.168.0.1)

**Comment by huaichao569** [comment]
My vs is  Microsoft Visual Studio Community 2022 .
version is 17.6.5.

**Comment by Deviaphan** [comment]
windows and browser?

Add your build of 'versus.exe' to attachment, I'll check.

**Comment by huaichao569** [comment]
This is the built program:
[bin.zip](https://github.com/Deviaphan/Versus/files/12640169/bin.zip)
This is vc++ version:
![3](https://github.com/Deviaphan/Versus/assets/2987000/13b24db0-abf9-4d7a-a7c0-2cacac0320a6)

**Comment by Deviaphan** [comment]
Looks like something wrong with Qt version. 
![изображение](https://github.com/Deviaphan/Versus/assets/20601357/af5cb089-a7b6-4ce7-bc05-bd2e7b0077f9)

**Comment by Deviaphan** [comment]
Check Qt modules
![изображение](https://github.com/Deviaphan/Versus/assets/20601357/13a26f4a-b0c2-4d42-b2a3-1544a8971436)

**Comment by huaichao569** [comment]
I'll try.

**Comment by huaichao569** [comment]
Let me try

**Comment by huaichao569** [comment]
The same configuration as yours

**Comment by Deviaphan** [comment]
Binaries are different. Don't know why. Maybe you needs to update MSVC

![изображение](https://github.com/Deviaphan/Versus/assets/20601357/eab0e2a1-8347-4118-b8a9-08b257941283)

**Comment by huaichao569** [comment]
I don't know why, but thank you.

**Comment by Deviaphan** [comment]
You already edit project? I see opengl/d3d/translation libraries on your screenshot.
Try to run and compile default project without any edits. And try debug instead of release, or disable all linker optimizations.

**Comment by huaichao569** [comment]
This is the dependency dll I built automatically after using the command "windeployqt versus.exe"

**Comment by huaichao569** [comment]
I only have exe after building with vs.
How do dependent DLLS output together?

**Comment by Deviaphan** [comment]
manually copy from the qt directory (powershell script copy one by one, not windeployqt)
Without the necessary libraries, you would not be able to launch, that is, the problem is something else.
I don't have Qt in my environment variables. Try running it on a clean virtual machine.

**Comment by huaichao569** [comment]
ok

**Comment by huaichao569** [comment]
The program I built with qt6.4.3 worked fine

**Comment by Deviaphan** [comment]
Perhaps we have some different subversions of qt 6.6.0. I have the version dated April 15, 2023.
In general, it worked with version 5.x, I updated not out of necessity, but because I wanted to.

**Comment by huaichao569** [comment]
It is different.
I downloaded the latest 6.6.0 beta.
Maybe you're right.

**Comment by Deviaphan** [comment]
Good news!
I don't know why they don't change minor version numbers. I updated 6.6.0 few times

**Comment by huaichao569** [comment]
Yes.
I'll try again after they release a stable version of 6.6.0 .

**Comment by Deviaphan** [comment]
Fixed
![изображение](https://github.com/Deviaphan/Versus/assets/20601357/73193a20-3ce4-49fa-82eb-84fdc0eed9d1)
